package com.example.repository;

/**
 * Defines the contract for data access operations related to user accounts (Account entities).
 * This interface implements the core of the Repository Pattern, separating the application's
 * business logic (what the app can do) from the data access implementation (how it is done).

 * All methods related to database interaction, persistence, and retrieval of Account data
 * should be defined here.
 */
public interface AccountRepository {

    /**
     * Authenticates a user by checking the provided username and password against stored credentials.
     * * @param username The username (account name) to verify.
     * @param password The password to check.
     * @return {@code true} if the credentials match a stored account, {@code false} otherwise.
     */
    boolean authenticationForUser(String username, String password);

    /**
     * Creates a new user account in the persistence layer (database).
     * * @param firstname The first name of the user.
     * @param lastname The last name of the user.
     * @param ssn The user's social security number (used as a unique identifier).
     * @param password The password for the new account.
     * @return The {@code user_id} (primary key) generated by the database for the new account.
     * Returns {@code -1} or a value less than 1 if the creation failed.
     */
    int createAccount(String firstname,String lastname,String ssn, String password);

    /**
     * Updates the password for an existing user account identified by its ID.
     * * @param userId The unique ID of the user account to update.
     * @param newPassword The new password to set for the account.
     * @return {@code true} if the password was successfully updated (one row affected), {@code false} otherwise.
     */
    boolean updateAccount(int userId, String newPassword);

    /**
     * Deletes a user account from the persistence layer based on its ID.
     * * @param userId The unique ID of the user account to delete.
     * @return {@code true} if the account was successfully deleted (one row affected), {@code false} otherwise.
     */
    boolean deleteAccount(int userId);
}
